### ISSUE TITLE
[Ubuntu] Installing a specific version

### ISSUE THREAD

**Issue by ddetommaso** [open-cogsci/OpenSesame#679]
How can I install a specific version of Opensesame (3.2.8 for example) under Ubuntu ?

**Comment by eort** [comment]
You can download older releases from Github: https://github.com/smathot/OpenSesame/releases
On Ubuntu, it will usually be enough to download the archive, unzip it and run the opensesame (either directly or with python). 

Eduard

**Comment by smathot** [comment]
That's correct. (Ubuntu PPA repositories do not, unfortunately, retain old versions.) I'm closing this, because it's a question rather than an issue, and thus best addressed on the support forum.

**Comment by ddetommaso** [comment]
Hi @eort ,

thank you for your response, but on Ubuntu 18.04 there are missing dependencies.

@smathot I think it's an issue because, if the procedure described by @eort doesn't work, basically there is no way to run specific Opensesame versions on Ubuntu systems. And keeping fixed versions of software is quite important issue for experimenters.

I'd ask you to reopen the issue and to consider for next releases:
- to find a procedure for installing (running) a specific version of Opensesame on Ubuntu systems
- to add this procedure in the documentation

In the following my tentative to install Opensesame 3.2.8 on Ubuntu 18.04 using Python 2.7

`
git clone https://github.com/smathot/OpenSesame.git
git checkout release/3.2.8
python opensesame
`

get these errors for missing deps:

`
Gtk-Message: 11:21:26.278: Failed to load module "canberra-gtk-module"
[2019-11-07 11:21:26,422:theme:61:WARNING] theme 'None' does not exist, using 'default'
[2019-11-07 11:21:26,422:theme:232:WARNING] using default icon theme, icons may be missing
[2019-11-07 11:21:26,435:theme:168:WARNING] missing icon os-kill
[2019-11-07 11:21:26,443:theme:168:WARNING] missing icon object-merge
[2019-11-07 11:21:26,454:theme:168:WARNING] missing icon os-run
[2019-11-07 11:21:26,462:theme:168:WARNING] missing icon os-run-in-window
[2019-11-07 11:21:26,470:theme:168:WARNING] missing icon os-run-quick
[2019-11-07 11:21:26,481:theme:168:WARNING] missing icon os-overview
[2019-11-07 11:21:26,483:theme:168:WARNING] missing icon os-debug
/home/icub/s4hri-code/OpenSesame/libopensesame/syntax.py:124: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  d = yaml.load(m.group(u'info'))
[2019-11-07 11:21:26,553:theme:168:WARNING] missing icon notes
[2019-11-07 11:21:26,566:theme:168:WARNING] missing icon os-view-controls
[2019-11-07 11:21:26,566:theme:168:WARNING] missing icon os-view-controls
[2019-11-07 11:21:26,574:theme:168:WARNING] missing icon os-view-script
[2019-11-07 11:21:26,583:theme:168:WARNING] missing icon os-view-split
[2019-11-07 11:21:26,593:theme:168:WARNING] missing icon notepad
[2019-11-07 11:21:26,651:theme:168:WARNING] missing icon os-view-controls
[2019-11-07 11:21:26,683:qtitem_store:130:WARNING] - !!python/object:warnings.WarningMessage
  _category_name: YAMLLoadWarning
  category: !!python/name:yaml.YAMLLoadWarning ''
  file: null
  filename: /home/icub/s4hri-code/OpenSesame/libopensesame/plugins.py
  line: null
  lineno: 212
  message: !!python/object/apply:yaml.YAMLLoadWarning
  - calling yaml.load() without Loader=... is deprecated, as the default Loader is
    unsafe. Please read https://msg.pyyaml.org/load for full details.

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[2019-11-07 11:21:26,728:theme:168:WARNING] missing icon os-experiment
[2019-11-07 11:21:26,736:theme:168:WARNING] missing icon os-sequence
[2019-11-07 11:21:26,745:theme:168:WARNING] missing icon os-sketchpad
[2019-11-07 11:21:26,756:theme:168:WARNING] missing icon os-loop
[2019-11-07 11:21:26,757:theme:168:WARNING] missing icon os-sequence
[2019-11-07 11:21:26,758:theme:168:WARNING] missing icon os-sketchpad
[2019-11-07 11:21:26,766:theme:168:WARNING] missing icon os-feedback
[2019-11-07 11:21:26,774:theme:168:WARNING] missing icon os-sampler
[2019-11-07 11:21:26,782:theme:168:WARNING] missing icon os-synth
[2019-11-07 11:21:26,790:theme:168:WARNING] missing icon os-keyboard_response
[2019-11-07 11:21:26,798:theme:168:WARNING] missing icon os-mouse_response
[2019-11-07 11:21:26,806:theme:168:WARNING] missing icon os-logger
[2019-11-07 11:21:26,815:theme:168:WARNING] missing icon os-inline_script
[2019-11-07 11:21:26,975:theme:168:WARNING] missing icon os-coroutines
[2019-11-07 11:21:26,983:theme:168:WARNING] missing icon os-repeat_cycle
[2019-11-07 11:21:26,998:theme:168:WARNING] missing icon os-pygaze_stop_recording
[2019-11-07 11:21:27,006:theme:168:WARNING] missing icon os-pygaze_init
[2019-11-07 11:21:27,015:theme:168:WARNING] missing icon os-pygaze_drift_correct
[2019-11-07 11:21:27,023:theme:168:WARNING] missing icon os-pygaze_start_recording
[2019-11-07 11:21:27,031:theme:168:WARNING] missing icon os-pygaze_wait
[2019-11-07 11:21:27,039:theme:168:WARNING] missing icon os-pygaze_log
[2019-11-07 11:21:27,051:theme:168:WARNING] missing icon os-form_multiple_choice
[2019-11-07 11:21:27,059:theme:168:WARNING] missing icon os-form_text_input
[2019-11-07 11:21:27,068:theme:168:WARNING] missing icon os-form_text_display
[2019-11-07 11:21:27,076:theme:168:WARNING] missing icon os-form_consent
[2019-11-07 11:21:27,084:theme:168:WARNING] missing icon os-form_base
[2019-11-07 11:21:27,096:theme:168:WARNING] missing icon os-joystick
[2019-11-07 11:21:27,104:theme:168:WARNING] missing icon os-reset_feedback
[2019-11-07 11:21:27,112:theme:168:WARNING] missing icon os-touch_response
[2019-11-07 11:21:27,116:theme:168:WARNING] missing icon notes
[2019-11-07 11:21:27,432:theme:168:WARNING] missing icon os-inspector
[2019-11-07 11:21:27,438:markdown_parser:43:ERROR] Unable to import markdown, proceeding without markdown
[2019-11-07 11:21:27,582:theme:168:WARNING] missing icon os-run-browser
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/icub/s4hri-code/OpenSesame/opensesame_extensions/bug_report/bug_report.py", line 120, in captured_err
    self.tabwidget.open_markdown(md, title=_(u'Oops ...'))
  File "/home/icub/s4hri-code/OpenSesame/libqtopensesame/widgets/tab_widget.py", line 487, in open_markdown
    from libqtopensesame.widgets.webbrowser import webbrowser
  File "/home/icub/s4hri-code/OpenSesame/libqtopensesame/widgets/webbrowser.py", line 32, in <module>
    from PyQt4.QtWebKit import QWebView as WebView
ImportError: No module named QtWebKit

Original exception was:
Traceback (most recent call last):
  File "/home/icub/s4hri-code/OpenSesame/libqtopensesame/console/_ipython_console.py", line 148, in run
    from IPython.qt.console.rich_ipython_widget import RichIPythonWidget
ImportError: No module named IPython.qt.console.rich_ipython_widget
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/icub/s4hri-code/OpenSesame/opensesame_extensions/bug_report/bug_report.py", line 120, in captured_err
    self.tabwidget.open_markdown(md, title=_(u'Oops ...'))
  File "/home/icub/s4hri-code/OpenSesame/libqtopensesame/widgets/tab_widget.py", line 487, in open_markdown
    from libqtopensesame.widgets.webbrowser import webbrowser
  File "/home/icub/s4hri-code/OpenSesame/libqtopensesame/widgets/webbrowser.py", line 32, in <module>
    from PyQt4.QtWebKit import QWebView as WebView
ImportError: No module named QtWebKit

Original exception was:
Traceback (most recent call last):
  File "/home/icub/s4hri-code/OpenSesame/libqtopensesame/console/_ipython_console.py", line 197, in _on_ipython_imported
    kernel_manager = self._ipython_importer.QtInProcessKernelManager()
AttributeError: 'IPythonImporter' object has no attribute 'QtInProcessKernelManager'

`

**Comment by eort** [comment]
Hi, 

I am on Ubuntu 18.04 and it does work for me. Well, at least with python 2 and for directly downloading the zip file, rather than cloning the repository. In Python 3, I get a segmentation fault. It is true that if you just download the repository, some dependencies that are outside Opensesame itself are not being installed. You'll have to do this by hand. I haven't done it myself, but you could try to set up a miniconda environment based on the dependencies list that is published together with the release. See [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file). Just save the list as `.yml` file.

Aside of that, Sebastiaan's point is still valid. This question/issue is better discussed on the [forum](forum.cogsci.nl), as this is, in first instance, a question about something not working. If it turns out to really be a problem with Opensesame that needs fixing, there still can be a Github issue opened. 

Hope this helps. 

Eduard

**Comment by ddetommaso** [comment]
Hi @eort,

probably it works in your Ubuntu 18.04 because you have already all the requirements satisfied, which is not the case when you need to install Opensesame from scratch.

Regarding Sebastiaan's point, I understand that is surely better discussing questions in the forum, but of course my question wasn't just a question cause it highlights an issue, quite important in my opinion. I work intensively with Opensesame within my research team and I'd be happy to use it in the future, but the software still has important limitations that need to be addressed.

Anyway, I just finished working on a solution that answer my original question.
I wasn't completely happy of Conda so I build a Docker container with all the dependencies.

In the following the code for running Opensesame 3.2.8 on Ubuntu 18.04 (opengl in nvidia cards won't work with this image)

`export XSOCK=/tmp/.X11-unix
export XAUTH=/tmp/.docker.xauth
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

docker run -ti --rm \
                  -v $XSOCK:$XSOCK \
                  -v $XAUTH:$XAUTH \
                  --env "XAUTHORITY=${XAUTH}" \
                  --env="DISPLAY=${DISPLAY}" \
                  iitschri/opensesame:v3.2.8-runtime-py27-ubuntu18.04`
